"""Manifest-driven, one-pass AOT materialization.

The manifest is the complete source of reachability truth.  This module never
scans generated C and never manufactures a nearby M/X body.  Nodes selected
for AOT are emitted exactly once; every other known node remains represented
by a NULL dispatch-table slot and therefore executes through LLE.
"""

from __future__ import annotations

import hashlib
import json
import pathlib
import re
from collections import defaultdict
from dataclasses import dataclass
from typing import Iterable, Mapping

from snes65816 import vector_table_offset

from .atomic_output import AtomicOutputDir, write_if_changed
from .codegen import (
    set_force_variant_at,
    set_emitted_names,
    set_name_resolver,
    set_rom_size,
    set_trampoline_returns,
    set_valid_variants,
    take_rejected_call_targets,
    take_trampoline_returns,
    take_unresolved_call_targets,
)
from .decoder import (
    clear_decode_cache,
    set_active_inline_arg_map,
    set_decode_cache_enabled,
)
from .emit_bank import BankEntry, emit_bank, _default_file_header
from .link_closure import assert_closed
from .program_analysis import NodeDisposition, ProgramManifest, VariantKey
from .translation_units import (_TOP_LEVEL_CPU_FN_RE,
                                write_bank_translation_units)


CACHE_FORMAT_VERSION = 5

# ── Program modules ──────────────────────────────────────────────────────────
# One generated tree is one PROGRAM MODULE: a dispatch table, its RAM-routine
# guards and every AOT body they point at, plus a descriptor naming the ROM
# image it was generated from. A host may link several modules (stock title +
# content variants such as BS Deluxe or Super Mario All-Stars) into one
# executable and choose between them at run time through
# runner/src/program_module.h. Two modules can only coexist in one link if
# their generated symbols do not collide, so a module may carry a PREFIX: every
# generated definition -- and every direct call to one -- is then renamed
# `<prefix>_<name>` through `module_namespace.h`, which every translation unit
# of that module includes first. The header is derived from the emitted text
# itself (the set of top-level `RecompReturn|void <name>(CpuState *cpu)`
# definitions), so it is authoritative rather than a regex run after the fact.
_MODULE_ID_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,62}$")
_MODULE_PREFIX_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]{0,31}$")
_VARIANT_SUFFIX_RE = re.compile(r"_M[01]X[01]$")
_MODULE_GLOBAL_SYMBOLS = (
    "g_dispatch_table",
    "g_dispatch_table_count",
    "g_ram_routine_guards",
    "g_ram_routine_guard_count",
    "g_program_module",
    "snes_program_module_register_generated",
)
MODULE_NAMESPACE_HEADER = "module_namespace.h"
MODULE_DESCRIPTOR_SOURCE = "module_v2.c"


def validate_module_identity(module_id: str, module_prefix: str | None):
    if not _MODULE_ID_RE.match(module_id or ""):
        raise ValueError(
            f"invalid module id {module_id!r}: use letters, digits, '.', '_' "
            "or '-' (at most 63 characters)")
    if module_prefix is not None and not _MODULE_PREFIX_RE.match(module_prefix):
        raise ValueError(
            f"invalid module prefix {module_prefix!r}: it becomes part of a C "
            "identifier, so use [A-Za-z_][A-Za-z0-9_]* (at most 32 characters)")


def collect_bank_symbols(source: str) -> list[str]:
    """Base names of every top-level generated function in one bank's text.

    `Foo_M1X1` and `Foo` (a void alias) both reduce to `Foo`; the namespace
    header then renames the base and all four (m, x) variants so a call to a
    variant that some OTHER bank defines still lands on the prefixed symbol.
    """
    bases = set()
    for match in _TOP_LEVEL_CPU_FN_RE.finditer(source):
        bases.add(_VARIANT_SUFFIX_RE.sub("", match.group(1)))
    return sorted(bases)


def emit_module_namespace(prefix: str, bases: Iterable[str]) -> str:
    lines = [
        "/* Auto-generated by snesrecomp v2 program_emit. Do NOT hand-edit.",
        " *",
        f" * Compile-time namespace for program module prefix `{prefix}`:",
        " * every generated definition AND every direct call to one is",
        " * renamed so this module can be linked beside another generated",
        " * module. Derived from the emitted translation units themselves. */",
        "#pragma once",
        "",
    ]
    names = set(_MODULE_GLOBAL_SYMBOLS)
    for base in bases:
        names.add(base)
        for m in (0, 1):
            for x in (0, 1):
                names.add(f"{base}_M{m}X{x}")
    for name in sorted(names):
        lines.append(f"#define {name} {prefix}_{name}")
    lines.append("")
    return "\n".join(lines)


def emit_module_descriptor(module_id: str, module_prefix: str | None,
                           rom_size: int, rom_sha256_hex: str) -> str:
    """The generated half of a SnesProgramModule: identity + table pointers.

    Registration runs from a constructor so the runtime sees every linked
    module before main(); the counts are read at that moment rather than
    folded into a static initializer, because `g_dispatch_table_count` is a
    `const unsigned` defined in another translation unit and therefore not a
    C constant expression.
    """
    digest = bytes.fromhex(rom_sha256_hex)
    if len(digest) != 32:
        raise ValueError("module descriptor needs a SHA-256 hex digest")
    lines = [
        "/* Auto-generated by snesrecomp v2 program_emit. Do NOT hand-edit.",
        " *",
        f" * Program module `{module_id}`"
        + (f" (symbol prefix `{module_prefix}_`)." if module_prefix else "."),
        " * Registers this generated tree's dispatch/guard tables with the",
        " * runtime module registry (runner/src/program_module.h) so a host",
        " * can select it by id. */",
        "#include <string.h>",
        "",
        "#include \"cpu_state.h\"",
        "#include \"program_module.h\"",
    ]
    if module_prefix:
        lines.append(f"#include \"{MODULE_NAMESPACE_HEADER}\"")
    lines.extend([
        "",
        "extern const DispatchEntry g_dispatch_table[];",
        "extern const unsigned g_dispatch_table_count;",
        "extern const RamRoutineGuard g_ram_routine_guards[];",
        "extern const unsigned g_ram_routine_guard_count;",
        "",
        "SnesProgramModule g_program_module;",
        "",
        "SNES_PROGRAM_MODULE_CONSTRUCTOR(snes_program_module_register_generated) {",
        f"  g_program_module.id = \"{module_id}\";",
        f"  g_program_module.symbol_prefix = "
        + (f"\"{module_prefix}\";" if module_prefix else "\"\";"),
        "  g_program_module.dispatch = g_dispatch_table;",
        "  g_program_module.dispatch_count = g_dispatch_table_count;",
        "  g_program_module.guards = g_ram_routine_guards;",
        "  g_program_module.guard_count = g_ram_routine_guard_count;",
        f"  g_program_module.rom_size = {rom_size}u;",
        "  {",
        "    static const uint8_t digest[32] = {",
    ])
    for i in range(0, 32, 8):
        chunk = ", ".join(f"0x{b:02x}" for b in digest[i:i + 8])
        lines.append(f"      {chunk},")
    lines.extend([
        "    };",
        "    memcpy(g_program_module.rom_sha256, digest, sizeof(digest));",
        "  }",
        "  snes_program_module_register(&g_program_module);",
        "}",
        "",
    ])
    return "\n".join(lines)
_HOST_CALL_RE = re.compile(r"\b([A-Za-z_]\w*(?:_M[01]X[01])?)\s*\(")
_SUFFIX_RE = re.compile(r"^(.*)_M([01])X([01])$")
_HOST_RUNTIME_DISPATCH_RE = re.compile(
    r"\bcpu_dispatch_(?:call_pc(?:_pushed)?|pc(?:_from|_paired)?)\s*"
    r"\(\s*[^,]+,\s*(0x[0-9A-Fa-f]+|[0-9]+)[uUlL]*")
_HOST_ALIAS_RE = re.compile(
    r"\bvoid\s+([A-Za-z_]\w*)\s*\(CpuState\s*\*cpu\)\s*;"
    r"[^\n]*?/\*\s*\$([0-9A-Fa-f]{2}):([0-9A-Fa-f]{4})\s+alias\s*\*/")
_PROFILE_MX_RE = re.compile(r"M([01])X([01])$")


def _lorom_mirror_pc24(pc24: int):
    bank = (pc24 >> 16) & 0xFF
    if bank < 0x40 or 0x80 <= bank < 0xC0:
        return ((bank ^ 0x80) << 16) | (pc24 & 0xFFFF)
    return None


def _architectural_interrupt_pcs(rom: bytes) -> frozenset[int]:
    """Return native/emulation NMI+IRQ vector entries and bank mirrors."""
    vector_base = vector_table_offset(rom)
    if len(rom) < vector_base + 0x20:
        return frozenset()
    result = set()
    for offset in (0x0A, 0x0E, 0x1A, 0x1E):
        pc = rom[vector_base + offset] | (rom[vector_base + offset + 1] << 8)
        if pc in (0, 0xFFFF):
            continue
        result.add(pc)
        result.add(0x800000 | pc)
    return frozenset(result)


def _cfg_for_bank(cfg_by_bank, bank: int):
    cfg = cfg_by_bank.get(bank & 0xFF)
    if cfg is not None:
        return cfg
    mirror = (bank & 0xFF) ^ 0x80
    if (bank & 0xFF) < 0x40 or 0x80 <= (bank & 0xFF) < 0xC0:
        return cfg_by_bank.get(mirror)
    return None


@dataclass(frozen=True)
class EmissionResult:
    emitted_banks: int
    reused_banks: int
    emitted_variants: int
    lle_variants: int


def _host_aliases(parsed):
    aliases = {}
    cfg_dirs = {pathlib.Path(path).resolve().parent for _bank, path, _cfg in parsed}
    for cfg_dir in sorted(cfg_dirs):
        header = cfg_dir / "funcs.h"
        try:
            source = header.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        for name, bank, pc in _HOST_ALIAS_RE.findall(source):
            aliases[name] = (int(bank, 16) << 16) | int(pc, 16)
    return aliases


def _cfg_name_maps(parsed):
    name_for_pc = {}
    canonical_for_pc = {}
    templates_exact = {}
    templates_any = {}
    cfg_by_bank = {}
    host_aliases = _host_aliases(parsed)
    claimed_names = set(host_aliases)
    for name, pc24 in sorted(host_aliases.items()):
        name_for_pc[pc24] = name

    for bank, _path, cfg in parsed:
        cfg_by_bank[bank] = cfg
        for entry in cfg.entries:
            pc24 = (bank << 16) | (entry.start & 0xFFFF)
            templates_exact[(pc24, entry.entry_m & 1,
                             entry.entry_x & 1)] = entry
            templates_any.setdefault(pc24, entry)
            canonical_for_pc.setdefault(
                pc24, (entry.entry_m & 1, entry.entry_x & 1))
            if entry.name and entry.name not in claimed_names:
                name_for_pc.setdefault(pc24, entry.name)
                claimed_names.add(entry.name)

    # Cross-bank `name <addr> <friendly>` declarations (cfg_loader only
    # auto-promotes IN-bank name decls into cfg.entries; a decl whose
    # address lives in a different bank than the cfg that declares it stays
    # declaration-only, see cfg_loader.load_bank_cfg). These are naming
    # hints only here -- they never manufacture a root or change what the
    # manifest analyzer considers reachable, unlike v1/v2_regen's
    # cross-bank auto-promote into emit entries.
    #
    # The same PC is frequently named from multiple cfgs (a bank-switch
    # wrapper reached via JSL from several callers, each with its own
    # cross-bank `name` line for documentation). Two DISTINCT PCs can also
    # claim the SAME friendly name -- e.g. a `func Foo <bodyPC>` in the
    # owning bank plus a cross-bank `name <wrapperPC> Foo` in a caller's
    # cfg, where Foo is really a PHB/PHK-wrapper around a differently
    # named body (see CLAUDE.md's wrapper-bypass note and v2_regen.py's
    # "Track friendly-name claims GLOBALLY" comment for the historical
    # background: v2_regen promotes cross-bank names into cfg.entries
    # guarded by the identical first-seen-wins rule implemented here).
    # Emitting two C functions under the same symbol is a hard build
    # break (MSVC C2084 same-TU / LNK2005 cross-TU), so claim names
    # globally and deterministically: first PC to claim a name (by bank
    # order, then by declaration order within a cfg) keeps it; any later,
    # DISTINCT PC that would reuse an already-claimed name falls back to
    # the emitter's synthetic bank_<BB>_<AAAA> name instead of colliding.
    for bank, _path, cfg in parsed:
        for nd in cfg.names:
            pc24 = nd.addr_24 & 0xFFFFFF
            if pc24 in name_for_pc:
                continue
            if not nd.name or nd.name in claimed_names:
                continue
            name_for_pc[pc24] = nd.name
            claimed_names.add(nd.name)
    for bank, _path, cfg in parsed:
        for nd in getattr(cfg, "symbols", ()):
            pc24 = nd.addr_24 & 0xFFFFFF
            if pc24 in name_for_pc:
                continue
            if not nd.name or nd.name in claimed_names:
                continue
            name_for_pc[pc24] = nd.name
            claimed_names.add(nd.name)
    return (name_for_pc, canonical_for_pc, templates_exact,
            templates_any, cfg_by_bank)


def discover_host_roots(parsed, source_roots: Iterable[pathlib.Path],
                        *, excluded_roots=()) -> tuple[VariantKey, ...]:
    """Infer the ROM entry variants called by handwritten host C.

    Host calls are outside the ROM architecture and therefore cannot be found
    by the decoder.  They are nevertheless discoverable build inputs, not
    per-game semantic hints. Generated output and build trees are excluded.
    """
    name_to_entries = defaultdict(list)
    aliases = _host_aliases(parsed)
    canonical_by_name = {}
    for bank, _path, cfg in parsed:
        for entry in cfg.entries:
            if entry.name:
                canonical_by_name.setdefault(
                    entry.name, (entry.entry_m & 1, entry.entry_x & 1))
                name_to_entries[entry.name].append((
                    (bank << 16) | (entry.start & 0xFFFF),
                    entry.entry_m & 1, entry.entry_x & 1))
    for name, pc24 in aliases.items():
        m, x = canonical_by_name.get(name, (1, 1))
        name_to_entries[name] = [(pc24, m, x)]

    excluded = []
    for root in excluded_roots:
        try:
            excluded.append(pathlib.Path(root).resolve())
        except OSError:
            pass

    roots = set()
    for source_root in source_roots:
        source_root = pathlib.Path(source_root)
        if not source_root.exists():
            continue
        paths = [source_root] if source_root.is_file() else source_root.rglob("*.c")
        for path in paths:
            try:
                resolved = path.resolve()
            except OSError:
                continue
            if any(resolved == root or root in resolved.parents
                   for root in excluded):
                continue
            if any(part.lower() in {"build", ".git", "generated", "gen"}
                   for part in resolved.parts):
                continue
            try:
                source = path.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
            for target_text in _HOST_RUNTIME_DISPATCH_RE.findall(source):
                pc24 = int(target_text, 0) & 0xFFFFFF
                roots.update(VariantKey(pc24, m, x)
                             for m in (0, 1) for x in (0, 1))
            for called in _HOST_CALL_RE.findall(source):
                suffix = _SUFFIX_RE.fullmatch(called)
                base = suffix.group(1) if suffix else called
                candidates = name_to_entries.get(base, ())
                if suffix:
                    wanted = (int(suffix.group(2)), int(suffix.group(3)))
                    roots.update(VariantKey(pc24, *wanted)
                                 for pc24, _m, _x in candidates)
                else:
                    # An unsuffixed C shim is an architectural host boundary,
                    # not proof of cfg-canonical widths. NMI/IRQ in particular
                    # preserve the interrupted M/X state. Analyze every live
                    # combination; the emitted wrapper dispatches on runtime
                    # mirrors and tiers an absent exact body to LLE.
                    roots.update(
                        VariantKey(pc24, m, x)
                        for pc24, _canonical_m, _canonical_x in candidates
                        for m in (0, 1) for x in (0, 1))
    return tuple(sorted(roots))


def discover_profile_roots(manifest_paths: Iterable[pathlib.Path],
                           declared_entry_pcs: Iterable[int] = (),
                           force_lle_out: set[int] | None = None) \
        -> tuple[VariantKey, ...]:
    """Load clean runtime-observed targets as optional AOT roots.

    A coverage profile influences only materialization: it never authorizes
    behavior, changes decoding semantics, or removes the LLE fallback. Bailed
    observations are deliberately excluded because they are bug evidence, not
    proof that a target is executable code.

    A clean interpreter landing is also not, by itself, proof of a callable
    function boundary.  Computed returns, inline-argument continuations, and
    indirect jumps can all land in the middle of an enclosing function.  Such
    PCs are valid LLE resume points but acquire a false stack/return ABI if
    emitted as standalone C functions.  Promote only hardware call landings
    (``call_gap``) or targets independently declared as function boundaries.
    """
    declared = {int(pc) & 0xFFFFFF for pc in declared_entry_pcs}
    for pc in tuple(declared):
        mirror = _lorom_mirror_pc24(pc)
        if mirror is not None:
            declared.add(mirror)
    roots = set()
    profile_discoveries = []
    explicit_unsafe_targets = set()
    qualified_targets = set()
    qualified_targets_declared = False
    for path in manifest_paths:
        path = pathlib.Path(path)
        try:
            manifest = json.loads(path.read_text(encoding="utf-8"))
        except OSError as exc:
            raise ValueError(f"cannot read profile manifest {path}: {exc}") \
                from exc
        except json.JSONDecodeError as exc:
            raise ValueError(f"invalid profile manifest {path}: {exc}") \
                from exc
        schema = str(manifest.get("schema", ""))
        if not schema.startswith("snesrecomp tier2 coverage"):
            raise ValueError(
                f"unsupported profile manifest schema {schema!r} in {path}")
        discoveries = manifest.get("discoveries", ())
        if not isinstance(discoveries, list):
            raise ValueError(
                f"profile manifest discoveries must be a list in {path}")
        profile_discoveries.extend(
            item for item in discoveries if isinstance(item, dict))
        unsafe = manifest.get("unsafe_aot_targets", [])
        if not isinstance(unsafe, list):
            raise ValueError(
                f"profile manifest unsafe_aot_targets must be a list in {path}")
        for value in unsafe:
            try:
                target = int(str(value), 0) & 0xFFFFFF
            except (TypeError, ValueError):
                raise ValueError(
                    f"invalid unsafe AOT target {value!r} in {path}")
            explicit_unsafe_targets.add(target)
            mirror = _lorom_mirror_pc24(target)
            if mirror is not None:
                explicit_unsafe_targets.add(mirror)
        qualified = manifest.get("qualified_aot_targets")
        if qualified is not None:
            qualified_targets_declared = True
            if not isinstance(qualified, list):
                raise ValueError(
                    f"profile manifest qualified_aot_targets must be a list "
                    f"in {path}")
            for value in qualified:
                try:
                    target = int(str(value), 0) & 0xFFFFFF
                except (TypeError, ValueError):
                    raise ValueError(
                        f"invalid qualified AOT target {value!r} in {path}")
                qualified_targets.add(target)
                mirror = _lorom_mirror_pc24(target)
                if mirror is not None:
                    qualified_targets.add(mirror)

    # A later AOT trial can prove that a formerly clean target is not a safe
    # standalone C boundary: the generated body begins at that target, then
    # its own dynamic edge bails. Treat the bailout's site as a target
    # blacklist across the whole profile set. This closes the feedback loop
    # without requiring a person to edit an earlier clean call-gap row.
    unsafe_targets = set(explicit_unsafe_targets)
    for item in profile_discoveries:
        try:
            bail_hits = int(item.get("bail_hits", 0))
            site = int(str(item["site_pc24"]), 0) & 0xFFFFFF
        except (KeyError, TypeError, ValueError):
            continue
        if bail_hits <= 0:
            continue
        unsafe_targets.add(site)
        mirror = _lorom_mirror_pc24(site)
        if mirror is not None:
            unsafe_targets.add(mirror)

    for item in profile_discoveries:
        if not isinstance(item, dict):
            continue
        try:
            clean_hits = int(item.get("clean_hits", 0))
            bail_hits = int(item.get("bail_hits", 0))
        except (TypeError, ValueError):
            continue
        if clean_hits <= 0 or bail_hits != 0:
            continue
        match = _PROFILE_MX_RE.fullmatch(str(item.get("entry_mx", "")))
        if match is None:
            continue
        try:
            target = int(str(item["target_pc24"]), 0) & 0xFFFFFF
        except (KeyError, TypeError, ValueError):
            continue
        if target in unsafe_targets:
            continue
        if (qualified_targets_declared and target not in qualified_targets
                and force_lle_out is not None):
            force_lle_out.add(target)
            mirror = _lorom_mirror_pc24(target)
            if mirror is not None:
                force_lle_out.add(mirror)
        if (str(item.get("site_kind", "")) != "call_gap" and
                target not in declared):
            continue
        roots.add(VariantKey(
            target, int(match.group(1)), int(match.group(2))))
    return tuple(sorted(roots))


def _copy_entry(template, *, name, pc24, m, x) -> BankEntry:
    if template is None:
        return BankEntry(name=name, start=pc24 & 0xFFFF,
                         entry_m=m, entry_x=x)
    return BankEntry(
        name=name,
        start=pc24 & 0xFFFF,
        end=template.end,
        entry_m=m,
        entry_x=x,
        tail_call_pc16=template.tail_call_pc16,
        entry_s_offset=template.entry_s_offset,
    )


def build_emission_entries(manifest: ProgramManifest, parsed,
                           *, enable_hle: bool = True):
    (name_for_pc, canonical_for_pc, templates_exact,
     templates_any, cfg_by_bank) = _cfg_name_maps(parsed)
    entries_by_bank = defaultdict(list)
    emitted = defaultdict(set)

    for key, node in sorted(manifest.nodes.items()):
        bank = (key.pc24 >> 16) & 0xFF
        cfg = _cfg_for_bank(cfg_by_bank, bank)
        pc16 = key.pc24 & 0xFFFF
        has_hle = bool(enable_hle and cfg is not None and (
            pc16 in getattr(cfg, "hle_func", {}) or
            pc16 in getattr(cfg, "hle_spc_upload", ())))
        if node.disposition != NodeDisposition.AOT_ELIGIBLE and not has_hle:
            continue
        # An HLE annotation replaces the architectural boundary, not one
        # decoder specialization of it.  Runtime P.M/P.X can legitimately
        # differ from the mode analysis observed (and the same boundary can
        # be entered through a LoROM execution mirror).  Falling back to LLE
        # for an absent exact slot would execute the ROM body instead of the
        # declared override.  Materialize the tiny HLE shim for every exact
        # M/X combination whenever any live manifest demand reaches it.
        modes = ((0, 0), (0, 1), (1, 0), (1, 1)) if has_hle else (
            (key.m, key.x),)
        for m, x in modes:
            if (m, x) in emitted[key.pc24]:
                continue
            template = templates_exact.get(
                (key.pc24, m, x), templates_any.get(key.pc24))
            mirror_pc24 = _lorom_mirror_pc24(key.pc24)
            if template is None and mirror_pc24 is not None:
                template = templates_exact.get(
                    (mirror_pc24, m, x), templates_any.get(mirror_pc24))
            name = name_for_pc.get(
                key.pc24, f"bank_{bank:02X}_{pc16:04X}")
            entries_by_bank[bank].append(_copy_entry(
                template, name=name, pc24=key.pc24, m=m, x=x))
            emitted[key.pc24].add((m, x))

    # Every analyzed PC is a known executable entry even when it had no cfg
    # label.  Give it the same deterministic synthetic name used by emission
    # and the dispatch table so cross-boundary branches can resolve to an AOT
    # tail call (or exact LLE fallback) instead of an unresolved-goto trap.
    for key in sorted(manifest.nodes):
        name_for_pc.setdefault(
            key.pc24,
            f"bank_{(key.pc24 >> 16) & 0xFF:02X}_{key.pc24 & 0xFFFF:04X}")

    # Keep each friendly alias bound to its cfg-canonical exact variant even
    # though other exact variants sort lexically before it.
    for bank, entries in entries_by_bank.items():
        mirror_bank = bank ^ 0x80
        entries.sort(key=lambda entry: (
            entry.start & 0xFFFF,
            0 if (entry.entry_m & 1, entry.entry_x & 1) ==
                 canonical_for_pc.get(
                     (bank << 16) | (entry.start & 0xFFFF),
                     canonical_for_pc.get(
                         (mirror_bank << 16) | (entry.start & 0xFFFF)))
                 else 1,
            entry.entry_m & 1, entry.entry_x & 1))
    return entries_by_bank, {
        pc24: frozenset(modes) for pc24, modes in emitted.items()
    }, name_for_pc, cfg_by_bank


def _fnv1a_u32(data: bytes) -> int:
    """FNV-1a over `data`, matching the runtime C `ram_routine_hash`
    (runner/src/snes/interp_bridge.c) so the guard hashes agree."""
    h = 2166136261
    for b in data:
        h = ((h ^ b) * 16777619) & 0xFFFFFFFF
    return h


def _collect_ram_routines(parsed):
    """Deduplicate ram_routine declarations across banks by pc24 (first wins)."""
    seen = {}
    for _bank, _path, cfg in parsed:
        for rr in getattr(cfg, "ram_routines", ()):  # noqa: B009
            seen.setdefault(rr.pc24, rr)
    return [seen[pc] for pc in sorted(seen)]


def emit_dispatch_table(manifest: ProgramManifest, emitted_variants: Mapping,
                        name_for_pc: Mapping[int, str],
                        inline_arg_map: Mapping[int, int],
                        ram_routines=()) -> str:
    known_pcs = sorted({key.pc24 for key in manifest.nodes})

    def base_name(pc24):
        return name_for_pc.get(
            pc24, f"bank_{(pc24 >> 16) & 0xFF:02X}_{pc24 & 0xFFFF:04X}")

    lines = [
        "/* Auto-generated from the authoritative LLE/AOT manifest. */",
        "#include \"cpu_state.h\"",
        "",
    ]
    for pc24 in known_pcs:
        base = base_name(pc24)
        for m, x in sorted(emitted_variants.get(pc24, ())):
            lines.append(f"RecompReturn {base}_M{m}X{x}(CpuState *cpu);")
    lines.extend(["", "const DispatchEntry g_dispatch_table[] = {"])
    if not known_pcs:
        lines.append("    { 0xFFFFFFu, { NULL, NULL, NULL, NULL }, 0 },")
    for pc24 in known_pcs:
        base = base_name(pc24)
        slots = ["NULL"] * 4
        for m, x in emitted_variants.get(pc24, ()):
            slots[(m << 1) | x] = f"{base}_M{m}X{x}"
        inline_n = inline_arg_map.get(
            pc24, inline_arg_map.get(pc24 ^ 0x800000, 0))
        lines.append(
            f"    {{ 0x{pc24:06X}u, {{ {', '.join(slots)} }}, "
            f"{inline_n} }},  /* {base} */")
    lines.extend([
        "};",
        "",
        "const unsigned g_dispatch_table_count =",
        "    (unsigned)(sizeof(g_dispatch_table) / sizeof(g_dispatch_table[0]));",
        "",
    ])

    # RAM-routine guards: for a WRAM-resident AOT body ($7E/$7F), runtime
    # dispatch is allowed ONLY when the live WRAM bytes still hash-match the
    # exact snapshot that was recompiled. Any mismatch -> the faithful
    # interpreter floor runs the real bytes (loud fallback). A RAM dispatch row
    # without a matching guard is never bounced to.
    #
    # A single ram_routine blob can expose more than one entry: a declared
    # `ram_routine` seeds its entry, but the analyzer may also materialize an
    # AOT body for a mid-routine resume PC that falls inside the same region
    # (e.g. SMW's $7F812E, a partial OAM clear inside the $7F8000 routine). Emit
    # a guard for EVERY emitted WRAM node, verifying it from its own entry to
    # the end of the covering region (a suffix of the snapshot) so no populated
    # WRAM dispatch row can ever be reached unguarded.
    regions = sorted((rr.pc24, rr.pc24 + len(rr.data), rr.data)
                     for rr in ram_routines)
    guards = []
    for pc24 in sorted(k for k in emitted_variants
                       if ((k >> 16) & 0xFF) in (0x7E, 0x7F)):
        covering = next(((b, e, d) for (b, e, d) in regions if b <= pc24 < e),
                        None)
        if covering is None:
            # An emitted WRAM node with no covering ram_routine cannot have
            # been decoded (no byte source); nothing to guard. Skip defensively.
            continue
        base, end, data = covering
        guards.append((pc24, end - pc24, _fnv1a_u32(data[pc24 - base:])))
    lines.append("const RamRoutineGuard g_ram_routine_guards[] = {")
    if not guards:
        lines.append("    { 0xFFFFFFFFu, 0u, 0u },")
    for pc24, glen, ghash in guards:
        lines.append(
            f"    {{ 0x{pc24:06X}u, {glen}u, 0x{ghash:08X}u }},  "
            f"/* {name_for_pc.get(pc24, '')} */")
    lines.extend([
        "};",
        "",
        "const unsigned g_ram_routine_guard_count =",
        "    (unsigned)(sizeof(g_ram_routine_guards) /"
        " sizeof(g_ram_routine_guards[0]));",
        "",
    ])
    return "\n".join(lines)


def _stable_hash(value) -> str:
    data = json.dumps(value, sort_keys=True, separators=(",", ":")).encode()
    return hashlib.sha256(data).hexdigest()


def _bank_cache_key(bank: int, manifest: ProgramManifest,
                    generator_digest: str, config_digest: str,
                    helpers: Mapping, inline_args: Mapping,
                    enable_hle: bool, host_alias_entries: Mapping,
                    shard_threshold_bytes: int, shard_pc_span: int,
                    module_prefix: str | None = None) -> str:
    nodes = [
        (key.manifest_key, node.digest, node.disposition.value)
        for key, node in sorted(manifest.nodes.items())
        if ((key.pc24 >> 16) & 0xFF) == bank
    ]
    return _stable_hash({
        "format": CACHE_FORMAT_VERSION,
        "bank": bank,
        "nodes": nodes,
        "exit_modes": [
            (key.manifest_key, pair[0] & 1, pair[1] & 1)
            for key, pair in sorted(manifest.exit_modes.items())
        ],
        "exit_mode_sets": [
            (key.manifest_key,
             sorted((m & 1, x & 1) for m, x in mode_set))
            for key, mode_set in sorted(manifest.exit_mode_sets.items())
        ],
        "generator": generator_digest,
        "config": config_digest,
        "helpers": sorted((int(k), str(v)) for k, v in helpers.items()),
        "inline_args": sorted((int(k), int(v)) for k, v in inline_args.items()),
        "host_aliases": sorted(
            (name, int(pc24), sorted((int(m), int(x)) for m, x in modes),
             bool(is_interrupt))
            for name, (pc24, modes, is_interrupt)
            in host_alias_entries.items()
            if ((pc24 >> 16) & 0xFF) == bank
        ),
        "hle": bool(enable_hle),
        "sharding": [int(shard_threshold_bytes), int(shard_pc_span)],
        "module_prefix": module_prefix or "",
    })


def emit_program(*, rom: bytes, parsed, manifest: ProgramManifest,
                 dispatch_helpers: Mapping, inline_arg_map: Mapping,
                 out_dir: pathlib.Path, manifest_text: str,
                 generator_digest: str, config_digest: str,
                 analysis_input_digest: str,
                 callee_exit_mx: Mapping | None = None,
                 callee_exit_mx_modes: Mapping | None = None,
                 enable_hle: bool = True,
                 shard_threshold_bytes: int = 4 * 1024 * 1024,
                 shard_pc_span: int = 0x0800,
                 check_link_closure: bool = True,
                 module_id: str = "main",
                 module_prefix: str | None = None,
                 rom_sha256_hex: str | None = None) -> EmissionResult:
    validate_module_identity(module_id, module_prefix)
    if rom_sha256_hex is None:
        rom_sha256_hex = hashlib.sha256(rom).hexdigest()
    entries_by_bank, emitted, name_for_pc, cfg_by_bank = build_emission_entries(
        manifest, parsed, enable_hle=enable_hle)
    cfg_dirs = sorted({pathlib.Path(path).resolve().parent
                       for _bank, path, _cfg in parsed})
    all_banks = sorted(set(cfg_by_bank) | set(entries_by_bank))
    root_pcs = {key.pc24 for key in manifest.roots}
    interrupt_pcs = _architectural_interrupt_pcs(rom)
    host_alias_entries = {
        name: (pc24, emitted.get(pc24, ()), pc24 in interrupt_pcs)
        for name, pc24 in _host_aliases(parsed).items()
        if pc24 in root_pcs
    }

    live_cache_path = pathlib.Path(out_dir) / ".snesrecomp-cache.json"
    try:
        old_cache = json.loads(live_cache_path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        old_cache = {}
    old_bank_keys = old_cache.get("banks", {})
    old_bank_outputs = old_cache.get("bank_outputs", {})
    old_output_hashes = old_cache.get("outputs", {})
    old_bank_symbols = old_cache.get("bank_symbols", {})
    new_bank_symbols = {}
    bank_file_header = None
    if module_prefix:
        def bank_file_header(bank):  # noqa: E306 - closure over the prefix
            return (_default_file_header(bank)
                    + f"#include \"{MODULE_NAMESPACE_HEADER}\"\n")

    workspace = AtomicOutputDir(pathlib.Path(out_dir))
    staging = workspace.staging
    assert staging is not None
    emitted_banks = 0
    reused_banks = 0
    new_bank_keys = {}
    new_bank_outputs = {}
    planned_bank_outputs = set()
    try:
        clear_decode_cache()
        set_decode_cache_enabled(True)
        set_rom_size(len(rom))
        set_name_resolver(dict(name_for_pc))
        # The same map, unaliased: what each body is really called.
        set_emitted_names(dict(name_for_pc))
        set_force_variant_at({})
        set_valid_variants(emitted, authoritative=True)
        set_trampoline_returns(set())
        set_active_inline_arg_map(dict(inline_arg_map) or None)
        take_unresolved_call_targets()
        take_rejected_call_targets()
        take_trampoline_returns()

        for bank in all_banks:
            cache_key = _bank_cache_key(
                bank, manifest, generator_digest, config_digest,
                dispatch_helpers, inline_arg_map, enable_hle,
                host_alias_entries, shard_threshold_bytes, shard_pc_span,
                module_prefix)
            new_bank_keys[f"{bank:02X}"] = cache_key
            previous_names = old_bank_outputs.get(f"{bank:02X}", ())
            reusable_output = bool(previous_names) and all(
                old_output_hashes.get(name)
                and (staging / name).is_file()
                and hashlib.sha256((staging / name).read_bytes()).hexdigest()
                    == old_output_hashes[name]
                for name in previous_names)
            # A reused bank contributes its recorded symbols to the module
            # namespace; a cache too old to record them must be re-emitted, or
            # the namespace header would silently omit that bank's symbols.
            previous_symbols = old_bank_symbols.get(f"{bank:02X}")
            if (old_bank_keys.get(f"{bank:02X}") == cache_key
                    and reusable_output and previous_symbols is not None):
                names = tuple(sorted(previous_names))
                new_bank_outputs[f"{bank:02X}"] = list(names)
                new_bank_symbols[f"{bank:02X}"] = list(previous_symbols)
                planned_bank_outputs.update(names)
                reused_banks += 1
                continue

            cfg = _cfg_for_bank(cfg_by_bank, bank)
            indirect_dispatch = {}
            if cfg is not None:
                for directive in getattr(cfg, "indirect_dispatch", ()):
                    indirect_dispatch[(bank << 16) |
                                      (directive["site_pc16"] & 0xFFFF)] = directive
            indirect_call_tables = (
                getattr(cfg, "indirect_call_tables", None)
                if cfg is not None else None)
            terminal_jsr_sites = None
            if cfg is not None and getattr(cfg, "terminal_jsr", None):
                terminal_jsr_sites = {
                    (bank << 16) | (site & 0xFFFF)
                    for site in cfg.terminal_jsr
                }
            noreturn_jsr_sites = None
            if cfg is not None and getattr(cfg, "noreturn_jsr", None):
                noreturn_jsr_sites = {
                    (bank << 16) | (site & 0xFFFF)
                    for site in cfg.noreturn_jsr
                }
            if indirect_call_tables:
                remapped_tables = dict(indirect_call_tables)
                for site, value in indirect_call_tables.items():
                    site_bank = (site >> 16) & 0xFF
                    if site_bank != bank and site_bank == (bank ^ 0x80):
                        remapped_tables[
                            (bank << 16) | (site & 0xFFFF)] = value
                indirect_call_tables = remapped_tables
            data_regions = (
                list(getattr(cfg, "data_regions", ()) or ())
                if cfg is not None else None)
            if data_regions:
                for region_bank, start, end in tuple(data_regions):
                    if region_bank != bank and region_bank == (bank ^ 0x80):
                        data_regions.append((bank, start, end))
            source = emit_bank(
                rom, bank, entries_by_bank.get(bank, []),
                dispatch_helpers=dict(dispatch_helpers) or None,
                indirect_call_tables=indirect_call_tables,
                indirect_dispatch=indirect_dispatch or None,
                terminal_jsr_sites=terminal_jsr_sites,
                noreturn_jsr_sites=noreturn_jsr_sites,
                data_regions=data_regions,
                exclude_ranges=(getattr(cfg, "exclude_ranges", None)
                                if cfg is not None else None),
                callee_exit_mx=dict(callee_exit_mx or {}),
                callee_exit_mx_modes=dict(callee_exit_mx_modes or {}),
                hle_spc_upload=(getattr(cfg, "hle_spc_upload", None)
                                if enable_hle and cfg is not None else None),
                hle_func=(getattr(cfg, "hle_func", None)
                          if enable_hle and cfg is not None else None),
                hle_dispatch=(getattr(cfg, "hle_dispatch", None)
                              if enable_hle and cfg is not None else None),
                inline_arg_map=dict(inline_arg_map) or None,
                declared_entry_pcs=(
                    {entry.start & 0xFFFF for entry in cfg.entries}
                    if cfg is not None else None),
                host_alias_entries=host_alias_entries,
                file_header=(bank_file_header(bank)
                             if bank_file_header else None),
            )
            new_bank_symbols[f"{bank:02X}"] = collect_bank_symbols(source)
            symbol_pcs = {
                (entry.name or
                 f"bank_{bank:02X}_{entry.start & 0xFFFF:04X}"):
                    entry.start & 0xFFFF
                for entry in entries_by_bank.get(bank, ())
            }
            symbol_pcs.update({
                name: pc24 & 0xFFFF
                for name, (pc24, _modes, _interrupt)
                in host_alias_entries.items()
                if ((pc24 >> 16) & 0xFF) == bank
            })
            names, _changes = write_bank_translation_units(
                staging, bank, symbol_pcs, source,
                threshold_bytes=max(0, int(shard_threshold_bytes)),
                pc_span=max(0, int(shard_pc_span)))
            new_bank_outputs[f"{bank:02X}"] = list(names)
            planned_bank_outputs.update(names)
            emitted_banks += 1

        planned = {
            *planned_bank_outputs,
            "dispatch_v2.c",
            "unresolved_stubs_v2.c",
            MODULE_DESCRIPTOR_SOURCE,
        }
        if module_prefix:
            planned.add(MODULE_NAMESPACE_HEADER)
            # A prefixed module resolves `#include "funcs.h"` to ITS OWN
            # declarations: the copy beside its translation units wins the
            # quote-include search over the stock module's recomp/funcs.h, so
            # two modules never share one header.
            planned.add("funcs.h")
        else:
            # A module that stopped being prefixed must not leave the old
            # namespace behind: with no include referencing it, a stale header
            # is harmless to the compiler and misleading to a reader.
            for stale_name in (MODULE_NAMESPACE_HEADER, "funcs.h"):
                stale_path = staging / stale_name
                if stale_path.exists():
                    stale_path.unlink()
        # Older game integrations used title-specific generated names such as
        # zelda_00_v2.c. Remove every obsolete generated-v2 translation unit
        # inside the staging tree, never from the live directory in place.
        for stale in staging.glob("*_v2.c"):
            if stale.name not in planned:
                stale.unlink()

        write_if_changed(
            staging / "dispatch_v2.c",
            emit_dispatch_table(manifest, emitted, name_for_pc, inline_arg_map,
                                ram_routines=_collect_ram_routines(parsed)))
        write_if_changed(
            staging / "unresolved_stubs_v2.c",
            "/* Manifest-driven generation: unresolved execution remains LLE. */\n")
        write_if_changed(
            staging / MODULE_DESCRIPTOR_SOURCE,
            emit_module_descriptor(module_id, module_prefix, len(rom),
                                   rom_sha256_hex))
        if module_prefix:
            all_bases = sorted({
                base for bases in new_bank_symbols.values() for base in bases
            } | set(host_alias_entries))
            write_if_changed(staging / MODULE_NAMESPACE_HEADER,
                             emit_module_namespace(module_prefix, all_bases))
            funcs_sources = [d / "funcs.h" for d in cfg_dirs
                             if (d / "funcs.h").is_file()]
            if not funcs_sources:
                raise ValueError(
                    "a prefixed module needs its own funcs.h beside its cfg "
                    f"files (looked in {', '.join(map(str, cfg_dirs))}); run "
                    "tools/v2_sync_funcs_h.py for that cfg directory first")
            write_if_changed(
                staging / "funcs.h",
                "/* Copied per module by program_emit from "
                f"{funcs_sources[0].name} in the module's cfg directory; the "
                "quote-include search finds this copy before any other "
                "module's header. */\n"
                + funcs_sources[0].read_text(encoding="utf-8",
                                             errors="replace"))
        write_if_changed(staging / "program_manifest.json", manifest_text)
        # Count analyzed architectural variants, not the additional exact HLE
        # shims synthesized for runtime modes absent from the manifest.  Those
        # shims are required override ABI coverage, not newly discovered AOT
        # work, and must not make the reported LLE count negative.
        emitted_count = sum(
            1 for key in manifest.nodes
            if (key.m, key.x) in emitted.get(key.pc24, ()))
        output_names = sorted(planned | {"program_manifest.json"})
        output_hashes = {
            name: hashlib.sha256((staging / name).read_bytes()).hexdigest()
            for name in output_names
        }
        cache = {
            "format_version": CACHE_FORMAT_VERSION,
            "generator_digest": generator_digest,
            "config_digest": config_digest,
            "analysis_input_digest": analysis_input_digest,
            "banks": new_bank_keys,
            "bank_outputs": new_bank_outputs,
            "bank_symbols": new_bank_symbols,
            "module": {"id": module_id, "prefix": module_prefix or ""},
            "outputs": output_hashes,
            "stats": {
                "roots": len(manifest.roots),
                "emitted_variants": emitted_count,
                "lle_variants": len(manifest.nodes) - emitted_count,
                "banks": len(all_banks),
            },
        }
        write_if_changed(
            staging / ".snesrecomp-cache.json",
            json.dumps(cache, indent=2, sort_keys=True) + "\n")
        # Gate the swap, not the caller's next command. Checking staging means
        # a tree that cannot link is never published over one that can: the
        # raise propagates through the `finally` below, which discards
        # staging and leaves the live directory exactly as it was.
        if check_link_closure:
            assert_closed(staging, display_dir=workspace.target)
        workspace.publish()
    finally:
        workspace.cleanup()
        clear_decode_cache()

    return EmissionResult(
        emitted_banks=emitted_banks,
        reused_banks=reused_banks,
        emitted_variants=emitted_count,
        lle_variants=len(manifest.nodes) - emitted_count,
    )
